-- BEAN Protocol: profiles, social connections, beanpot announcements
-- Run against a fresh Supabase project or existing DB (idempotent where possible)

-- Profiles: wallet-linked profile data (username, bio, images)
CREATE TABLE IF NOT EXISTS public.profiles (
  wallet_address text PRIMARY KEY,
  username text,
  bio text,
  pfp_url text,
  banner_url text,
  updated_at timestamptz DEFAULT now()
);

-- RLS: app uses anon key; read public, write via API (signature/OAuth/cron verified server-side)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Profiles readable by everyone" ON public.profiles;
CREATE POLICY "Profiles readable by everyone"
  ON public.profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Profiles writable by anon" ON public.profiles;
CREATE POLICY "Profiles writable by anon"
  ON public.profiles FOR ALL USING (true) WITH CHECK (true);

-- Social connections: Discord/Twitter linked to wallet
CREATE TABLE IF NOT EXISTS public.social_connections (
  wallet_address text PRIMARY KEY,
  discord_id text,
  discord_username text,
  twitter_id text,
  twitter_handle text,
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.social_connections ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Social connections readable by everyone" ON public.social_connections;
CREATE POLICY "Social connections readable by everyone"
  ON public.social_connections FOR SELECT USING (true);

DROP POLICY IF EXISTS "Social connections writable by anon" ON public.social_connections;
CREATE POLICY "Social connections writable by anon"
  ON public.social_connections FOR ALL USING (true) WITH CHECK (true);

-- Beanpot announcements: tracks which rounds have been announced to Discord
CREATE TABLE IF NOT EXISTS public.beanpot_announcements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  round_id bigint NOT NULL UNIQUE,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.beanpot_announcements ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Beanpot announcements readable by everyone" ON public.beanpot_announcements;
CREATE POLICY "Beanpot announcements readable by everyone"
  ON public.beanpot_announcements FOR SELECT USING (true);

DROP POLICY IF EXISTS "Beanpot announcements writable by anon" ON public.beanpot_announcements;
CREATE POLICY "Beanpot announcements writable by anon"
  ON public.beanpot_announcements FOR ALL USING (true) WITH CHECK (true);

-- Index for beanpot cron lookups
CREATE INDEX IF NOT EXISTS idx_beanpot_announcements_round_id
  ON public.beanpot_announcements (round_id);
